### ISSUE TITLE
will you support the obsidian callout

### ISSUE THREAD

**Issue by 668168** [oprypin/markdown-callouts#15] opened 2022-12-03 04:06 UTC
# Example usage
```
> [!INFO]
> Here's a callout block.
> It supports **markdown**, [[Internal link|wikilinks]], and [[Embed files|embeds]]!
> ![[og-image.png]]
```

# Detail syntax:
https://help.obsidian.md/How+to/Use+callouts

**Comment by oprypin** [comment] 2023-12-15 15:18
Duplicate of #13

**Closed by oprypin** 2023-12-15 15:18 UTC
